### PR TITLE
Convert co.wrap() to async/await

### PR DESCRIPTION
**Pull request by jacksteamdev**
Thought it might be a good idea to update to `async/await`, so I've run [this codemod](https://github.com/albinekb/co-to-async) to convert the usage of `co.wrap()` to `async/await`.

Loving PlopJS! Thanks for all the hard work y'all have put into this.

### CODE REVIEW

**Comment by crutchcorn** [comment]
This seems like an awesome update to remove a dep that hasn't been updated in some time! Let me pull it into a local copy of `plop` and see if I can get it working as-expected (I know tests ran, but with a change as large as this I'd like to reallllly check, ya know?)

**Comment by crutchcorn** [comment]
This works fantastically with all of the `plop` examples! This is great, thank you so much! :D

**Comment by crutchcorn** [comment]
Actually, this isn't a huge deal it's taken me all of 5 minutes to fix, I will mention that said codemod did NOT remove default imports of `co` as such:

```
import co from 'co';
```

From our ava tests. Just wanted to give heads up in case you were planning on running this codemod anytime soon :) Thanks again for the contribution!

**Comment by jacksteamdev** [comment]
Sorry about that, good to know!

**Comment by amwfl** [comment]
Thanks! that's awesome.

**Pull request merged**
