### PR TITLE
adds all prompt types from inquirer

### PR DESCRIPTION
**Pull request by zonzujiro**
Hey, guys! :)

`inquirer` has a lot more types of questions, so I have transferred them here.

It will not cover custom prompts, ofc. But at least default should be covered.

### CODE REVIEW

**Comment by crutchcorn** [comment]
I hate to've done this to you, but I _just_ merged in a PR for adding TS typing tests. Are you able to rebase/merge `master` to fix the conflict, but can you also add typings to verify your changes?

**Comment by zonzujiro** [comment]
No problem. Will solve :)

**Comment by zonzujiro** [comment]
@crutchcorn done!

**Comment by zonzujiro** [comment]
Closed by mistake.

I see some weird errors on CI - locally, typescript allows to import `inquirer.CheckboxQuestion`

**Comment by armand1m** [comment]
@zonzujiro the @types/inquirer dependency of the repository is outdated. Updating it to ^6.5.0 fixes this issue.

Just as a shout out: I'm incorporating your changes in my PR #165, hope you don't mind!

**Pull request closed without merging**
