### PR TITLE
Enable linting for index.d.ts

### PR DESCRIPTION
**Pull request by jacksteamdev**
I was looking at `index.d.ts` and realized that eslint wasn't configured to parse it. `@typescript-eslint` has gotten pretty good lately, so I've installed the necessary dependencies and done the configuration for it.

This requires a barebones `tsconfig.json` (which has comments explaining), and I switched the eslint config from `json` to `js` so it would be easier to read, hopefullly this is ok.

A few minor linting errors showed up in `index.d.ts`, which were easy to fix.

### CODE REVIEW

**Comment by jacksteamdev** [comment]
Looks like the checks have failed, I'll look into this, so don't bother until I've got it working.

**Comment by jacksteamdev** [comment]
OK, looks like docker image `circleci/node:8.9.4-browsers` is [used for the checks (line 30)](https://circleci.com/gh/plopjs/node-plop/486#config/containers/0), but `@typescript-eslint` requires a minimum of node 8.10.0:

https://github.com/typescript-eslint/typescript-eslint/blob/9edd863b2a66ee44bd4a439903973e6c207480aa/packages/eslint-plugin/package.json#L12

So that's what's making the tests fail.

**Comment by crutchcorn** [comment]
This overall LGTM, I particularly appreciate the comments in the tsconfig file. @amwmedia we'll need to update the CircleCI before merging, I don't have permissions on it

**Comment by jacksteamdev** [comment]
I forgot we update the CircleCI configs in `.circleci`. 😳

**Comment by crutchcorn** [comment]
So did I, evidently 😅

**Pull request merged**
