### PR TITLE
Improve windows support

### PR DESCRIPTION
**Pull request by ArchiCroc**
I ran into trouble getting plop to work as expected on my windows machine.  I traced the root cause to window's paths using backslashes and that conflicting with the escape character for handlebars.

In my case, The addMany action was generating paths like "c:\project\something\\{{ pascalCase name }}.js.hbs" that were not being translated correctly.  I added a normalizePath helper to convert these back to posix style paths when it detects it's running on windows.

Also, when I pulled the repo, many tests failed due to the 'del' package no longer supporting windows style paths.  I wrapped the paths passed on to 'del' in the same normalizePath helper.

Another issue I found running the tests was that windows does not mark files executable the same way unix does. I'm not sure the best solution here, but I attempted to skip those tests when running on win32.

### CODE REVIEW

**Comment by acoates-ms** [comment]
I'd love to get this in too.  We've been hitting the same issue.

**Comment by kenotron** [comment]
Pinging @amwmedia - would you mind merging this one?

**Comment by kenotron** [comment]
@ArchiCroc - I think rather than taking a fork, maybe it's a good thing to create a new action type so we can just consume this "fix" as a package for now until @amwmedia takes the fix... something like "addManyCrossPlatform" action keeping the same options, etc.

**Comment by amwmedia** [comment]
sorry for the delay guys. merged 👍

**Comment by acoates-ms** [comment]
Any idea on when a publish will happen?

**Comment by amwmedia** [comment]
I'm hoping tomorrow

**Pull request merged**
